baseURL = 'https://sametk0ca.github.io/'
languageCode = 'en-us'
title = 'Samet Koca Blog'
theme = 'papermod'

[params]
  defaultTheme = "dark"
  description = "Cyber Security Blog & Writeups"
  author = "Samet Koca"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  
  [params.profileMode]
    enabled = true
    title = "Samet Koca"
    subtitle = "Cyber Security Enthusiast"
    imageUrl = "/avatar.jpg"
    imageWidth = 180
    imageHeight = 180

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/sametk0ca"

  [[params.socialIcons]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/samet-koca-7b3033188/"

  [[params.socialIcons]]
    name = "Email"
    url = "mailto:samet.kocats@gmail.com"

[menu]
  [[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "Whoami"
    url = "/about/"
    weight = 50

[markup.highlight]
  noClasses = false
  style = "dracula"
  tabWidth = 4
  lineNos = true
  guessSyntax = true
